name: Browser Tests

on: push

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: test
        uses: cypress-io/github-action@v2
        with:
          parallel: true
          browser: chrome
